apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeatconf
data:
  filebeat.yml: |-
    filebeat.inputs:
    - input_type: log
      paths:
        - /data/log/*/*.log
      tail_files: true
      fields:
        pod_name: '${podName}'
        pod_ip: '${podIp}'
        pod_deploy_name: '${podDeployName}'
        pod_namespace: '${podNamespace}'
    output.elasticsearch:
      hosts: ["https://10.104.54.238:9200"] #替换为elasticsearch-master.efk:9200 的地址
      protocol: "https"
      ssl.verification_mode: "none"
      username: "elastic"
      password: "WVch8DMgTaK4GEgD"
      topic: "filebeat-sidecar"
      codec.json:
        pretty: false
      keep_alive: 30s
